name: Tests
on: push
jobs:
  contract-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        env:
          VITE_API_KEY: ${{ secrets.API_KEY }}
        run: npm test